### PR TITLE
Added /home path to the BRUTE_DOC_ROOT_PREFIXES

### PR DESCRIPTION
**Pull request by tanaydin**
This small change only adds /home to the BRUTE_DOC_ROOT_PREFIXES which also can be used as document root.

### CODE REVIEW

**Comment by stamparm** [comment]
sorry, haven't seen this kind of deployment till now

**Comment by tanaydin** [comment]
sure, one of my tests I'm faced that kind of setting but it's up to you.

**Comment by stamparm** [comment]
`/home/index.php` or whatever?

**Comment by tanaydin** [comment]
I need to check again, will keep you updated.

**Comment by tanaydin** [comment]
it was like

/home/foobar

**Pull request closed without merging**
