### PR TITLE
Fixed name 're' is not defined.

### PR DESCRIPTION
**Pull request by Arduino3128**
Fixed NameError: name 're' is not defined.
're' not imported in ./thirdparty/ansistrm/ansistrm.py

### CODE REVIEW

**Comment by fgeek** [comment]
Isn't it already imported when this is being used lib/core/patch.py and lib/core/log.py?

**Comment by Arduino3128** [comment]
Yes, it seems it is imported in lib/core/patch.py and lib/core/log.py but it is also needed to be imported in that file too?

**Comment by Arduino3128** [comment]
Fixed now.

**Comment by kiuyy77** [comment]
.


في الثلاثاء، 25 ماي، 2021 17:57 Kanad Nemade ***@***.***> كتب:

**Pull request closed without merging**
