### PR TITLE
Add 'randomcommentsextended' tamper script.

### PR DESCRIPTION
**Pull request by squarefractal**
This is similar to the randomcomments tamper script, but adds random strings within the comments.

### CODE REVIEW

**Comment by stamparm** [comment]
`randomcomments` should be removed because it is based on false assumption that /**/ can be put inside the SQL keyword. Can you please give one example where yours or `randomcomments` can work (which DBMS)?

**Comment by stamparm** [comment]
Only case where this could work if the WAF removes the `/*...*/` before sending the whole query to the DBMS. But I really doubt that this is realistic case.

**Comment by squarefractal** [comment]
I'm contributing this indeed keeping a broken WAF in mind, which is doing that exact thing you mention.

**Comment by stamparm** [comment]
No hard feelings :)

**Pull request closed without merging**
