### PR TITLE
Converting to python2.7 shebang

### PR DESCRIPTION
**Pull request by Xartrick**
Adding python2.7 instead of python.

### CODE REVIEW

**Comment by stamparm** [comment]
This won't go into official repository. sqlmap is supported by both python 2.6 and python 2.7.

**Comment by stamparm** [comment]
I am wondering why you proposed this in the first place? You want accept the changes to 313 files (all *.py). There must be a really good reason.

**Comment by Xartrick** [comment]
Can edit line to : `#!/usr/bin/env python2` instead.

I installed sqlmap on my Arch Linux and it cannot run using `./sqlmap.py`, it uses `#!/usr/bin/env python` who's Python 3 on my installation...

**Comment by stamparm** [comment]
`python2` is not recognized everywhere as an alias to Python v2.x
screenshot - 05112015 - 09 27 12 am

**Pull request closed without merging**
