### PR TITLE
Feature/compatible with py3/print

### PR DESCRIPTION
**Pull request by akun**
* Compatible with Python 3 step by step except `thirdparty`.
* run: `2to3 . -f print -n -w`

### CODE REVIEW

**Comment by akun** [comment]
Compatible with Python 3 step by step except `thirdparty`.

**Comment by akun** [comment]
```
2to3 . -f print -n -w
```

**Comment by stamparm** [comment]
I closed down other related pull requests because of two reasons:

1) When you are making this kind of pull requests (chained) it is "acceptable" to make a single (squashed) pull request than to make N different ones
2) There is no partial Python 3 coverage. Either it can be run in Python 3 or it can't be run. I am not sure that these couple of 2to3 done the job

**Comment by akun** [comment]
OK. I'll make a single PR and add some test.

Compatible with Python 3 may continued for a while.

**Comment by akun** [comment]
see: #2967

**Pull request closed without merging**
