### PR TITLE
Now it can retreive password hashes for MSSQL

### PR DESCRIPTION
**Pull request by iammosespaulr**
earlier .... it was unable to do so ...

### CODE REVIEW

**Comment by stamparm** [comment]
It doesn't work like this. You have a specific case. You haven't researched what were the differences and you are trying to change it for all.

**Comment by stamparm** [comment]
`sysxlogins` is covered with `query`, while `sql_logins` is covered with `query2`. You have JUST removed the usage of `fn_varbintohexstr` and mingled the order of execution.

To repeat. Without proper research you can't push this kind of changes.

**Comment by iammosespaulr** [comment]
well ... 
I'm sorry ... I just pushed it because ... It worked for me ... and It didn't work earlier ...
I'll generalise the solution and then push it ...
Thanks tho ... 😁

**Comment by stamparm** [comment]
What version of MsSQL was it?

**Comment by iammosespaulr** [comment]
it's MSSQL12 😁

**Comment by iammosespaulr** [comment]
this was the error which I got earlier tho ```(remote) (pymssql.ProgrammingError) (208, "Invalid object name 'master..sysxlogins'.DB-Lib error message 20018, severity 16:\nGeneral SQL Server error: Check messages from the SQL Server\n")```

**Comment by iammosespaulr** [comment]
#3418 ... do check this out ...

**Pull request closed without merging**
