### PR TITLE
Support for chunked requests

### PR DESCRIPTION
**Pull request by boy-hack**
refer:https://github.com/sqlmapproject/sqlmap/issues/3535
Bypassing some waf by using add headers for `Transfer-Encoding:Chunked`

I added a `--chunk` parameter option.when use it, it will convert all requests into chunks .
I defined the chunking keyword `CHUNKED_KEYWORDS` in `setting.py`, ensuring that each chunk does not contain a defined keyword.

### CODE REVIEW

**Comment by stamparm** [comment]
I like the idea, though, there are couple of things to discuss:

1) There is a missing reference to the (e.g.) https://github.com/icatproject/python-icat/blob/master/icat/chunkedhttp.py (or wherever this piece of code in `httphandler.py` has been "borrowed"). This should be added (either by yourself or myself)
2) Header of https://github.com/sqlmapproject/sqlmap/pull/3536/files#diff-6f4e181d662678e93a05b3a19d9cd7d6 has to be the same as in all other sqlmap's python files. Handle (@w8ay) or proper contributor name can be put inside the doc/THANKS.md
3) I would need to do some major re-vamping of the whole code as it doesn't meet the code-quality of the rest of sqlmap's code. This has nothing to do with the pull request. I am just warning that this has to be done (by myself)

**Comment by boy-hack** [comment]
Thank you, for your comment
1. Because `urllib2` does not support chunked, I hooked some functions from the `urllib2` and `httplib`, only I did it according to the source code of urllib2, no reference to other people's code.
2. I'm sorry. I have removed my personal information.
3. Good luck, I may be able to help with something.

**Comment by huitc** [comment]
Are you the guy named "w8ay"? @boyhack

**Comment by stamparm** [comment]
Closing this down because of missing reference for code in `lib/request/httphandler.py`. I politely asked and didn't get the straight answer. Referencing is just a manner of politeness

**Comment by stamparm** [comment]
First image (yours) and second image (https://github.com/icatproject/python-icat/blob/master/icat/chunkedhttp.py) have so much in common





p.s. people who don't reference other people's code/research/... are not welcome here

**Comment by boy-hack** [comment]
Ok, let me explain, I refer to urllib2 https://github.com/enthought/Python-2.7.3/blob/master/Lib/urllib2.py `AbstractHTTPHandler`  `do_request_`, rewrite it in order to support chunked.
I haven't read the code for https://github.com/icatproject/python-icat/blob/master/icat/chunkedhttp.py (before you show it to me), I guess it does the same thing with me.

**Comment by stamparm** [comment]
@boy-hack what to put inside `doc/THANKS`? `@boy-hack` or something else?

**Comment by stamparm** [comment]
p.s. @boy-hack thank you for this feature and sorry for my (deleted) rant

**Comment by stamparm** [comment]
p.p.s. added `w8ay` to [doc/THANKS.md](https://github.com/sqlmapproject/sqlmap/blob/master/doc/THANKS.md)

**Comment by boy-hack** [comment]
I am happy to use the name @boy-hack and it is my pleasure to contribute code to sqlmap great software :)

**Comment by boy-hack** [comment]
w8ay is also very good

**Pull request merged**
