### PR TITLE
Added commands stop, kill, list to API client

### PR DESCRIPTION
**Pull request by daremon**
Stop & kill were straightforward. For list:
- I removed the permission check (admin_id)
- I also list the task status

I kept it backwards compatible: you can still call list with the admin taskid and get the simple list back.

### CODE REVIEW

**Comment by stamparm** [comment]
Everything looks ok other than the removal of `is_admin` check. That is a security check so the end user couldn't mess up with other tasks (list, kill,...) if he doesn't know the magic "nonce" `Admin ID`.

**Comment by daremon** [comment]
OK, do you want me to put the check back and require the `admin_id` when executing `list`?

It would be nice if the server could tell you your tasks, but I can't think of a simple way to do it.

**Comment by stamparm** [comment]
Give me a little time. Will push the `simple way`

**Comment by stamparm** [comment]
With the latest commit you'll be able to do the `admin` stuff without knowing the `ADMIN id`. Only (safety) catch is that the tasks the (non-admin) user will be able to list/flush will be those that have the same `remote_addr` (same origin as the user itself).

One thing. In case that the user is hooked up for the first time, to avoid the `new` for `list` you can provide whatever you want for the task_id (e.g. `0`). I can do this afterwards in case that I am not clear enough

**Comment by daremon** [comment]
I think it works as expected now. BTW I changed the list command output to include the status of each task (line 386).

**Comment by lordpato** [comment]
Could you please check this? :

  File "api.py", line 387
    for x in list(DataStore.tasks)}
      ^
SyntaxError: invalid syntax

**Comment by stamparm** [comment]
That is not there. Please clone from the start.

Bye

**Pull request merged**
