### PR TITLE
add --servername option to support various of  bottle server adapter

### PR DESCRIPTION
**Pull request by dozysun**
add --servername option to support various of  bottle server adapter,   improve server concurrent

### CODE REVIEW

**Comment by stamparm** [comment]
Will take a look tomorrow

**Comment by stamparm** [comment]
shouldn't this option be called `--adapter`/`adapter`?

**Comment by dozysun** [comment]
yes,  it should be,   need i to change it or you do it ?

**Comment by stamparm** [comment]
I can do it later today (if you don't make it)

**Comment by dozysun** [comment]
have changed it already

**Pull request merged**
