### PR TITLE
Add Clickhouse support

### PR DESCRIPTION
**Pull request by 0x4144**
Hi :wave:,
This PR adds the ability the support of [Clickhouse](https://clickhouse.com/) dbms for all the techniques except for stacked queries which are not supported.

### CODE REVIEW

**Comment by stamparm** [comment]
@0x4144 nice. do you have some place so I could actually test it? if yes, you could drop it to me privately

**Comment by stamparm** [comment]
p.s. merged, but will need to do some more adjustments

**Comment by stamparm** [comment]
@0x4144 what to put into doc/THANKS.md?

usual format is:

```
John Doe, <john.doe(at)domain.com>
* for contributing support for ClickHouse
```

**Comment by 0x4144** [comment]
> @0x4144 what to put into doc/THANKS.md?
> 
> usual format is:
> 
> ```
> John Doe, <john.doe(at)domain.com>
> * for contributing support for ClickHouse
> ```

Hi, you can put Alexis Danizan, <alexis.danizan(at)synacktiv.com>. 
Thanks

**Pull request merged**
