### PR TITLE
add SafeLine waf detection

### PR DESCRIPTION
**Pull request by virusdefender**
https://www.chaitin.cn/en/safeline

http://safeline-demo.chaitin.cn/?id=1%20or%201=1

### CODE REVIEW

**Comment by stamparm** [comment]
Sorry man. I though that this was an Issue request :). Haven't spotted that it is a pull request

**Comment by stamparm** [comment]
As a matter of gratitude added you to the `doc/THANKS.md`

**Comment by virusdefender** [comment]
@stamparm 

I think you should `break` once retval is true

https://github.com/sqlmapproject/sqlmap/commit/1ed59267df4980fba729dc2dba1622f3e2367d03#diff-38960ee49a2da7fc754fe40c588afc17R17

**Comment by stamparm** [comment]
@virusdefender you are absolutely right. Done in haste. Patched with the last commit

**Comment by stamparm** [comment]
p.s. also added safeline here https://github.com/stamparm/identYwaf/commit/4b288406c6f4f5bd36bf4497b3cc4bcca36e89cd

**Pull request closed without merging**
