### PR TITLE
Websocket support of sqlmap #1198

### PR DESCRIPTION
**Pull request by RicterZ**

### CODE REVIEW

**Comment by brandonprry** [comment]
@RicterZ Do you have an example application you tested this against?

**Comment by RicterZ** [comment]
@brandonprry 
Try this:

    python2.7 sqlmap.py -u "ws://103.238.227.183:8888/" --data="*"

**Comment by stamparm** [comment]
@RicterZ it should be working now. Just one thing. If that server is yours (`103.238.227.183`) can you please update the `--data` to contain valid data?

**Comment by RicterZ** [comment]
@stamparm Done.

**Comment by stamparm** [comment]
I can't see the changes :)

I meant something like:

`python2.7 sqlmap.py -u "ws://103.238.227.183:8888/" --data="id=1"`

sqlmap now just blindly injects anything there (`--data=*`) without success in finding proper SQLi (it just recognizes MySQL from heuristics)

**Comment by RicterZ** [comment]
Sorry, I misunderstood.
But the message format of websocket is "123456" rather than "id=1".
The sql injection vector is the whole message you send.

**Comment by stamparm** [comment]
Ok. `123456` doesn't seem to be a valid value.

I get `{"text": "Failed to get table_schema of table_name: 123456, error: tuple index out of range"}`

Can you please state one valid value (that is working on the other side)?

**Comment by RicterZ** [comment]
Any `table_name` field in the `information_schema.tables` is valid.
Try `tables`:

    select table_schema from tables where table_name='tables';

**Pull request merged**
