### PR TITLE
Detecting errors when standard status code and custom reply

### PR DESCRIPTION
**Pull request by GovanifY**
This is a very simple PR which adds a new option, error-string, allowing sqlmap to detect SQL errors when the status code report is still correct(ie 200) but errors out, in the case that the error message outputted by the website has been customized by the sysadmin.

This is as quick of a PR as it can get, so tell me if there's any documentation I should fill out about this option or anything else!

### CODE REVIEW

**Comment by stamparm** [comment]
Two important things:

1) That piece of code that you've been referencing this pull request (with comment `generic SQL warning/error messages`) is just the **generic** "detector". Please take a look into the https://github.com/sqlmapproject/sqlmap/blob/master/data/xml/errors.xml to gather a better insight what is being done in the "non-generic department"
2) As I am not sure whether you've previously took a look into that same `errors.xml` file, instead of providing this kind of "option" (IMO it is of no use with all those error message regexes), maybe it would be better for you to provide examples where sqlmap actually failed to find those messages. That way I could improve the engine for all, instead of incorporating another option which would be used only by one or two people

**Comment by GovanifY** [comment]
Hey,
Unfortunately, this was done for a CTF in order to fool sqlmap explicitely. It wouldn't really help to give you the error message created specifically for that.
That's why I thought implementing this as an option, rather than adding hardcoded regexes, could be a better result in that kind of situation.

I would have another proposal following this reply: we have tamper scripts for creating custom payloads when you need a programmatical approach, why not allow tamper scripts to intercept replies? This would solve this use case along with others where, say, you have an encoded output returned in some way that cannot be resolved by sqlmap directly.

**Comment by stamparm** [comment]
https://github.com/sqlmapproject/sqlmap/wiki/Usage#preprocess-response-data

**Comment by GovanifY** [comment]
My bad, I actually didn't knew about that! Sorry for the bother

**Pull request closed without merging**
