### PR TITLE
Add --crawl-file option to specify output filename

### PR DESCRIPTION
**Pull request by ctshanghai**
Currently, there is no way to explicitly set the output file of crawling results.  For some automated tooling utilizing that feature, it is a bit more convenient to be able to control the output file name.

### CODE REVIEW

**Comment by stamparm** [comment]
Two things:

1) We already have tons of switches
2) sqlmap is not a crawling tool
3) If you opened a new Issue request I would put the prompt and asking where you want to store the crawling results

**Comment by ctshanghai** [comment]
That's fine, I'll close this pull request.  The issue with prompting is that it's requiring user interaction, which eliminates the usefulness in the context of automation.

**Comment by stamparm** [comment]
@ctshanghai can you please in future open a new Issue request, then we can discuss and afterwards if we agree you can do the pull request

**Comment by ctshanghai** [comment]
@stamparm of course, no problem.

Cheers.

**Pull request closed without merging**
